### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by kbrandwijk** [Urigo/graphql-cli#110]
To increase release quality, and to enable things like automerging deps.

**Comment by Urigo** [comment]
We've rewritten the whole codebase, but we still need to improve test coverage.
Opening again

**Comment by wtrocki** [comment]
This would be critical issue. I think the best approach for this would be to simply:

- run init
- generate all artifacts
- check if project compiles
- run server and make some calls to the backend

All can be done in circle/github actions.

**Comment by wtrocki** [comment]
I have added basic tests in #802

**Comment by wtrocki** [comment]
We have provided basic test coverage included automation. Because of the codebase is very small (most of the codegen code/config etc. is moved). I would be looking to get more coverage - not accepting PR's without tests but general issue is no longer needed.
