### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Artimunor** [Urigo/graphql-cli#1102]
**Describe the bug**
while using graphql-cli with a bit more complex schema, the following commands:
yarn graphql generate --backend
yarn graphql generate --db
yarn schemats generate

all went ok and generated outputs, however yarn graphql codegen gives me the following error:
→ Cannot read property 'name' of undefined

what could be causing it?

**To Reproduce**
1. install graphql-cli
2. initialize project
3. add interrelated entities to schema
4. yarn graphql generate --backend -> OK
5. yarn graphql generate --db -> OK
6. yarn schemats generate -> OK
7. yarn graphql codegen -> Error

**Expected behavior**
generated-types.ts to become overwritten with the objects from my own schema

**Screenshots**
![image](https://user-images.githubusercontent.com/6189700/80355120-f6b89880-8877-11ea-88c0-a0633c6671aa.png)

**Versions (please complete the following information):**
 - OS: Ubuntu 19.10 
 - graphql-cli: 4.0.1-beta.3

**Comment by ardatan** [comment]
Fixed in 4.0.1-beta.5
