### ISSUE TITLE
get-schema has no consistent order of properties

### ISSUE THREAD

**Issue by mastertinner** [Urigo/graphql-cli#111]
Every time I run `graphql get-schema`, the values of enums and the parameters of queries and mutations are sorted differently in `schema.graphql`. This leads to unnecessary changes in `git diff` when checking in the `schema.graphql` file. Shouldn't the order of enum values and query/mutation params be alphabetical and therefore consistent?

**Comment by schickling** [comment]
Good point. Would actually be interesting what should be the source of truth here. The server? A certain strategy in the GraphQL CLI?

**Comment by mastertinner** [comment]
That is a good point you're making, @schickling! I just checked using GraphiQL and there the params and enums are also not in alphabetical order. So maybe it's the server who messes the order up every time... I'm using https://github.com/graphql-go/handler. Do you think I should create the issue there instead?

**Comment by kbrandwijk** [comment]
I think we should strive to reduce diffs to a minimum. That being said, maybe we should aim for a server-independent standard for local schema storage. Alphabetical makes sense, Schema - Query - Mutation - Subscription - Interfaces - Unions - Types - Input Types - Enums, then alphabetical also makes sense.

**Comment by mastertinner** [comment]
I just created https://github.com/graphql-go/handler/issues/34 to order the properties coming from the Go library.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use GraphQL Code Generator plugin of GraphQL CLI with Codegen's `schema-ast` plugin. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new alpha version channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We've changed the `get-schema` command to use [GraphQL Code Generator](http://graphql-code-generator.com) plugin of GraphQL CLI with the Codegen's [`schema-ast` plugin](https://graphql-code-generator.com/docs/plugins/schema-ast). 

And for the `diff` we use [GraphQL Inspector](https://graphql-inspector.com) now.

Those tools should provide you with consistent output between runs.

Checkout new instructions in the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and let us know your feedback during that alpha period!

Feel free to contact us by opening a new issue or joining our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
