### ISSUE TITLE
Fresh full stack project init fails under linux

### ISSUE THREAD

**Issue by Artimunor** [Urigo/graphql-cli#1122]
**Describe the bug**
Fresh full stack project init fails under linux claiming a tmp directory can not be removed since it is not empty.

**To Reproduce**
1. Run `npx graphql-cli@next init` 
2. Answer the questions:
   -> Full Stack
   -> New Project
   -> Enter Name
   -> Full Stack Template

**Expected behavior**
the command `npx graphql-cli@next init` to deliver a generated full stack project

**Screenshots**
![image](https://user-images.githubusercontent.com/6189700/80828577-cd846900-8be5-11ea-83da-318e23d8665e.png)

**Versions (please complete the following information):**
 - OS: `Ubuntu 19.10`
 - graphql-cli: `4.0.1-beta.6`

**Suggestion**
Use `rm -rf <dirname>` instead

**Comment by ardatan** [comment]
Could you try to remove that directory manually and try again?

**Comment by Artimunor** [comment]
I removed it manually already, and i have watched the /tmp directory while doing the procedure.
This directory is being created by the procedure.

**Comment by kamilkisiela** [comment]
@Artimunor it's now fixed, try to use `v4.0.0` (latest).
