### ISSUE TITLE
Generate one file per ts type.

### ISSUE THREAD

**Issue by samuelcastro** [Urigo/graphql-cli#1249]
**Is your feature request related to a problem? Please describe.**
Right now all types are generated inside one single file, it would great to be able to provide a config value to be able to generate one type per file.

**Describe the solution you'd like**
To have the ability to generate one file per type.

**Describe alternatives you've considered**
I don't know any alternatives at the moment.

**Additional context**
none.

**Comment by wtrocki** [comment]
We got you covered! Our next release will allow this and many more. we are still testing it at the moment but expect update soon

**Comment by samuelcastro** [comment]
Hey @wtrocki, that's great, when should we expect that to be released?

Thanks!

**Comment by wtrocki** [comment]
@samuelcastro funny story is that we had that initially split towards single file but we needed to move as people started to complain about 200 generated files :D

Now we allow flexible model where most of the stuff is generated at runtime. 
Feel free to watch repo for updates: https://github.com/aerogear/graphback/

**Comment by samuelcastro** [comment]
Interesting I'll take a look.

**Comment by wtrocki** [comment]
going to close it as we will address it in graphback
