### ISSUE TITLE
How get scheme with headers Authorization?

### ISSUE THREAD

**Issue by Sergyus** [Urigo/graphql-cli#1314]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. `Windows 10`, `OS X High Sierra`, `Ubuntu 16.04`] 
 - `graphql-cli`: [e.g. `2.16.5`]
 - other packages if applicable

**Additional context**

**Comment by ardatan** [comment]
You don't provide any information but you can pass additional headers like below;
```yml
schema:
   - URL:
         headers:
            Authorization: ...
```

**Comment by k4mr4n** [comment]
@ardatan 
when I pass this I don't get the unauthorized error anymore but I get an empty screen on my "Graphql Execution Result" on the vscode,
vscode output console logs:

```
[Error - 8:08:53 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: A cached document cannot be found.
  Code: -32603 
10/4/2020, 8:08:54 PM [4] (pid: 36048) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///...file_path"}

undefined
Warning: endpoints missing from graphql config. will try 'schema' value(s) instead
```

Can you help me figure out what is the issue, please?

**Comment by felipeptcho** [comment]
For me, it worked using this config in the `.graphqlrc.json`:
```json
{
  "schema": [
    {
      "<your-schema-url>": {
        "headers": {
          "Authorization": "Token"
        }
      }
    }
  ]
}
```

Or this in the `.graphqlrc.yml` (pay attention to the indentation):
```yml
schema:
  - <your-schema-url>:
      headers:
        Authorization: Token
```

We need to add that to the documentation.

**Comment by ardatan** [comment]
Closing for now. Feel free to create a new one if it persists.
