### ISSUE TITLE
Yarn script with graphq lint -p project throw error

### ISSUE THREAD

**Issue by jhanitesh10** [Urigo/graphql-cli#1346]
**Describe the bug**

We have yarn script which does the lining for the generated schema[`lint: "graphql lint -p project"`].  
After upgrading from version 2.17.0 to 4.0.0 yarn linting script throwing the error 
`$ node index.js && graphql lint -p projectName
Did you mean init?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
zsh: exit 1     yarn generate`
If I run graphql lint -p project on cmd it works but running yarn script only throw the error.

Notes: Downgrading to version 3.0.14 from 4.0.0 solved this issue.

**To Reproduce**
1: Create a yarn script with linting the schema
2: Run the yarn script

**Versions (please complete the following information):**
 - OS: [`OS X High Sierra`] 
 - `graphql-cli`: [`4.0.0`]
 - `graphql`: [`15.3.0`]
 -  `@graphql-tools/load-files`: [`^6.0.15`]
 -  `@graphql-tools/merge`: [`6.0.15`]

**Additional context**
The problem is solved after downgrading to the graphq-cli version 3.0.14. Basically it works for version lower than 4.0.0. 
Thanks, everyone for the such a great tool :)

**Comment by wtrocki** [comment]
Thank you for logging the issue. GraphQL lint is no longer supported command. 
We are happy to review your suggestions on top of the new commands structures.

**Comment by wtrocki** [comment]
See validate command

**Comment by jhanitesh10** [comment]
Sure, Thanks for letting me know.
