### ISSUE TITLE
get-schema at version 4

### ISSUE THREAD

**Issue by cancng** [Urigo/graphql-cli#1393]
Hi. I was using "graphql get-schema -p prisma" for generating .graphql schema at version 3.0.14. But now, new version does not generate any schema with this command. 

How can I generate at new versions, thanks 😊

**Comment by ardatan** [comment]
You can see migration docs;
https://github.com/Urigo/graphql-cli/blob/master/docs/MIGRATION.md

**Comment by ardatan** [comment]
Feel free to submit a new issue if you have any problems.
