### ISSUE TITLE
Add query linting

### ISSUE THREAD

**Issue by cjoudrey** [Urigo/graphql-cli#14]
Opening this in case someone has time.

GraphQL schema linter: https://github.com/cjoudrey/graphql-schema-linter/
GraphQL query linter: https://github.com/apollographql/eslint-plugin-graphql/

**Comment by kbrandwijk** [comment]
I think this is sufficiently covered in #33 and can be closed?

**Comment by cjoudrey** [comment]
That’s so cool, didn’t know someone implement `lint`.

I think the missing part might be to also include query linting somehow?

**Comment by schickling** [comment]
Yup! @cjoudrey would you mind opening a PR for this?

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` 
We have bunch of commands for fixing and validating GraphQL files in the new structure.
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH
