### ISSUE TITLE
Improvements of init command

### ISSUE THREAD

**Issue by wtrocki** [Urigo/graphql-cli#1421]
After numerous feedback and questions init command was proven to be quite challenging to use due to numerous questions asked and inconsistent flows.

I think we need to rearange questions and ask if users want to start from scratch first or template. 
Then ask for the templates or type of project (if they choose existing ones).

This simple rearrangement will help us to minimize number of questions and get the real intentions right.

This should not be the first question of init 
<img width="310" alt="Screenshot 2020-09-04 at 10 46 25" src="https://user-images.githubusercontent.com/981838/92229932-26b91d80-eea2-11ea-9b20-0d1a3ec57293.png">

Where are your operation documents? etc. should not be called on template as templates by definition needs

**Comment by machi1990** [comment]
This is a great issue. +1 on trimming down a number of questions.  

> Where are your operation documents? etc. should not be called on template as templates by definition needs

This is true for most of our templates but it might not hold for some other templates provided via the `templateUrl` option. I think we should always ask for them if a template does not have the operation documents.

**Comment by wtrocki** [comment]
TemplateUrl seems also be off. Why you would use init if you have template. 
The work that init does is checks out the code. If there is template and you know github repo you can just check that out. 

I see init as way to discover those templates and get quick glimpse what templates are officially supported.

**Comment by machi1990** [comment]
> TemplateUrl seems also be off. Why we would use init if we have template URL and we can check it's source code. The work that init does is checks out the code. If there is template and you know github repo you can just check that out.

Yes, but the command init goes further than simply checking out the repo. Adding the necessary config and graphql-cli configs if needed.

**Comment by wtrocki** [comment]
Ah.. I was thinking that template should contain all ready to go config. The only thing different will be versions of packages that we bump/align?

**Comment by machi1990** [comment]
> Ah.. I was thinking that template should contain all ready to go config. The only thing different will be versions of packages that we bump/align?

Yes, this is true for the templates we propose but it might not be the case for other templates within the ecosystem.
