### ISSUE TITLE
graphql get-schema also downloads the schema for the server itself

### ISSUE THREAD

**Issue by kbrandwijk** [Urigo/graphql-cli#145]
Meaning: when you create a server, you'll have an 'app' project in your config, with your manually constructed schema. Currently, there is no way to tell the CLI that you don't want to download a schema for that project when running `graphql get-schema --all`.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use GraphQL Code Generator plugin of GraphQL CLI with Codegen's `schema-ast` plugin. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We've changed the `get-schema` command to use [GraphQL Code Generator](http://graphql-code-generator.com) plugin of GraphQL CLI with the Codegen's [`schema-ast` plugin](https://graphql-code-generator.com/docs/plugins/schema-ast). 

The new configuration using the [new GraphQL Config](https://medium.com/the-guild/graphql-config-708dd0e5d15f) should make that option easy to use.
Could you please verify that this is the case?

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during the alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
