### ISSUE TITLE
Extension discovery

### ISSUE THREAD

**Issue by kbrandwijk** [Urigo/graphql-cli#152]
Currently, the config extensions are hardcoded into the cli. I propose using a similar mechanism to plugin discovery (find installed packages starting with `graphql-cli`).

Plugins could export a `register` method, that could be run, similar to how the graphcool extension registers itself, by getting passed in the config object.

This would allow the CLI to open up to other extensions.

**Comment by FredyC** [comment]
So if I understand correctly it's not possible to have custom extensions now? I mean I would love to employ `https://github.com/dotansimha/graphql-code-generator` instead of `apollo-codegen`. Is that possible with plugins only?

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` .
We use GraphQL Code Generator for `codegen` command to generate typings and code from schema using various plugins of it.
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've also completely rewritten the actually implementation to make it easy to extend and change the default packages that the commands are using and add new commands!

We would love to hear feedback from library authors on the new design

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
