### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by heynemann** [Urigo/graphql-cli#156]
When installing graphql-cli I get the following error:

```
npm install -g graphql-cli
npm ERR! code ETARGET
npm ERR! notarget No matching version found for graphcool-json-schema@1.2.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'graphcool-yml'
npm ERR! notarget
```

**Comment by iamclaytonray** [comment]
Can you try adding it globally with Yarn to see if the same error occurs?

**Comment by iamclaytonray** [comment]
`yarn global add graphql-cli`

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0`
Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

This was a complete rewrite.

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during the alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
