### ISSUE TITLE
Improve `codegen` command & graphql-config integration for apollo-codegen

### ISSUE THREAD

**Issue by schickling** [Urigo/graphql-cli#165]
Codegen tools for GraphQL (both client-side & server-side) are becoming increasingly popular and provide a great DX. There are still a lot of open issues around the usage of `apollo-codegen` in combination with `graphql-cli` and `graphql-config`. This issue is meant as a collection of these issues so they can be found (and tackled) more easily:

- [ ] [graphql-cli-codegen](https://github.com/rricard/graphql-cli-codegen) seems to be outdated and should be updated to work with v2 of the GraphQL CLI
- [ ] The CLI plugin is currently not compatible with multiple projects
- [ ] Possibly add an interactive setup command for codegen

cc rricard

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` .
We use GraphQL Code Generator for `codegen` command to generate typings and code from schema using various plugins of it.
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We use [GraphQL Code Generator](http://graphql-code-generator.com) as the default package for the `codegen` command to generate typings and code from schema using it's various plugins.

We've also moved to use the new `alpha` version of [`graphql-config`](https://medium.com/the-guild/graphql-config-708dd0e5d15f) and now both tools can share their one config file!

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback. 

You can still change the default package for `codegen` from GraphQL Code Generator to Apollo's codegen.
If you want to keep using Apollo codegen and don't know how to do that, please open a new issue so we can track it and make sure it works and that it's documented properly.

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
