### ISSUE TITLE
text defect

### ISSUE THREAD

**Issue by markfirmware** [Urigo/graphql-cli#1689]
still

:::tip
Note: You can execute the command `graphql discover` to open a list of GraphQL CLI plugins you can still.

**Comment by ardatan** [comment]
Thanks! Would you create a PR for that change? ;)

**Comment by markfirmware** [comment]
My friend, I have no idea what your text is intended to say.

**Comment by ardatan** [comment]
You're pointing to a typo, right? So I was asking if you can create a PR to fix that.

**Comment by markfirmware** [comment]
Ok, my mistake.
