### ISSUE TITLE
Disable auto-open browser for 'graphql playground'

### ISSUE THREAD

**Issue by pokorson** [Urigo/graphql-cli#189]
Hi, is it possible to disable auto-opening browser tab each time after `graphql playground` command?

**Comment by kbrandwijk** [comment]
This might be implemented using a command line argument for `graphql playground`. @pokorson would you be interested in submitting a PR?

**Comment by schickling** [comment]
I think there’s also another option. If I remember correctly, CRA manages to simply re-focus the tab if it was previously opened. Regardless of we end up adding the described option or not, this should be implemented as well.

**Comment by kbrandwijk** [comment]
@schickling Can you move that into a separate issue?

**Comment by pokorson** [comment]
@schickling I think the way CRA does it depends on webpack and stuff like live-reload/hot-reload and uses websockets for communication. I think playground just opens a tab with server address

**Comment by schickling** [comment]
Moved re-focus discussion to #192

**Comment by pokorson** [comment]
@schickling It is annoying when I sometimes need to restart server multiple times and each time new tab appears and is focused. Also would it be possible to skip both opening tab and focus?

**Comment by schickling** [comment]
I see, that answers my question: I suggest someone creates a PR introducing a flag `-server-only` which just starts a server without opening the electron app or the browser.

**Comment by Aubron** [comment]
#190 has been merged, this is complete.
