### ISSUE TITLE
Re-focus browser tab when re-running `graphql playground`

### ISSUE THREAD

**Issue by schickling** [Urigo/graphql-cli#192]
When re-running `graphql playground` and there's already a playground browser tab opened, it should be re-focussed instead of opening an additional new tab (similar how CRA is implemented).

**Comment by Aubron** [comment]
I don't have time to figure this one out right now, but I do know that this has all the info one should need to complete this:

https://github.com/facebook/create-react-app/blob/next/packages/react-dev-utils/openBrowser.js

**Comment by wtrocki** [comment]
Closing as this is no longer valid (command do not exist anymore)
