### ISSUE TITLE
graphql get-schema fails when graphql module exists

### ISSUE THREAD

**Issue by dhenson02** [Urigo/graphql-cli#200]
`graphql-cli` uses version 0.12.3 of `graphql` and if the module exists in the project already (with a different version), the following will occur:

### console output

```zsh
☁  kiwi [studies-too] ⚡ graphql get-schema -p kiwi
✖ Cannot use GraphQLObjectType "__Directive" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```
Upgrading my version fixed the issue.  Might be helpful to try and catch this and tell the user to upgrade or maybe avoid it all together.

**Comment by testower** [comment]
Having a similar issue. Oddly doing an npm ls reveals both instances are actually sub-dependencies of graphql-cli, and they are the same version:

```
└─┬ graphql-cli@2.16.7
  ├─┬ apollo-codegen@0.19.1
  │ └── graphql@0.13.2
  └─┬ graphql-schema-linter@0.1.1
    └── graphql@0.13.2
```

**Comment by macs91** [comment]
@dhenson02 how did you get around this precisely?

**Comment by dhenson02** [comment]
Sorry @macs91 it was so long ago I don't remember the steps (if any) other than version changes, but I can tell you right now my project is successfully using these deps in `package.json` -

```json
  "dependencies": {
    ...
    "graphql": "^0.12.3",
    ...
  },
  "devDependencies": {
    ...
    "graphql-cli": "^2.13.2",
    ...
  }
```

**Comment by lorensr** [comment]
```
gql get-schema -e https://api.graphql.guide/graphql -o schema.json

⚠ Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

![image](https://user-images.githubusercontent.com/251288/53675546-57911480-3c65-11e9-8feb-d350c9543582.png)

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use GraphQL Code Generator plugin of GraphQL CLI with Codegen's `schema-ast` plugin. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new new alpha version channel for GraphQL CLI - `4.0.0-alpha.XXX` !

We've changed the `get-schema` command to use [GraphQL Code Generator](http://graphql-code-generator.com) plugin of GraphQL CLI with the Codegen's [`schema-ast` plugin](https://graphql-code-generator.com/docs/plugins/schema-ast). 

It was also a complete rewrite and all dependencies were updated.

Please let us know if the issue is still relevant in the new structure.

Checkout new instructions in the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and let us know your feedback during that alpha period!

Feel free to contact us by opening a new issue or joining our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
