### ISSUE TITLE
Support passing options to `opn`. E.g. force opening in Firefox when Safari is system default

### ISSUE THREAD

**Issue by JofArnold** [Urigo/graphql-cli#213]
See line here: https://github.com/graphql-cli/graphql-cli/blob/8a5e849cbe3b5ee747aa2ff4d637b4b052afe4bc/src/cmds/playground.ts#L97

See also https://github.com/graphql-cli/graphql-cli/issues/189 for further discussion of options.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` 
Checkout new instructions and we will be happy to hear your feedback. 
Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We have just released a new structure for GraphQL CLI in new alpha versions `4.0.0-alpha.XXX`.

This was a complete rewrite! 
Can you please see if this is still relevant with the new version?

Checkout the [new instructions](https://github.com/urigo/graphql-cli#usage--initialization) and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) on the docs and let us know your feedback. 

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
