### ISSUE TITLE
endpointName option getting passed to get-schema command using nps

### ISSUE THREAD

**Issue by donovanhiland** [Urigo/graphql-cli#228]
Running `graphql get-schema` from nps fails yargs validation passing an `endpointName` option through.

Issue opened on nps as well. See: https://github.com/kentcdodds/nps/issues/169

**Comment by donovanhiland** [comment]
So after digging in a little I have some more information. At some point during installation I got the error message:

```
You have to specify endpoint name or define GRAPHQL_CONFIG_ENDPOINT_NAME enviroment variable
```

So I went ahead and defined `GRAPHQL_CONFIG_ENDPOINT_NAME`. The problem with this it seems is that `yargs` is now parsing out `endpointName` and passing it down as an option. Which fails on `.strict()`. I'm not sure why this works with plain npm scripts and not with nps.

Changing my env var to `GRAPHQL_CONFIG_ENDPOINT` to match the expected command `endpoint` seems to work.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use GraphQL Code Generator plugin of GraphQL CLI with Codegen's `schema-ast` plugin. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We've changed the `get-schema` command to use [GraphQL Code Generator](http://graphql-code-generator.com) plugin of GraphQL CLI with the Codegen's [`schema-ast` plugin](https://graphql-code-generator.com/docs/plugins/schema-ast). 

Could you check if it works well for you in the new structure?

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during the alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
