### ISSUE TITLE
Support flutter

### ISSUE THREAD

**Issue by sachaarbonel** [Urigo/graphql-cli#234]
Feature request to support [flutter.io](https://flutter.io/)

Hi, I was wondering if it would be possibleto to add a flutter boilerplate in a near future? 
P.S. Sorry if it is not the right repo for this feature request

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0`
Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by wtrocki** [comment]
@Sach97 In current architecture community can build their own templates. The only requirement will be to generate dart specific plugins for graphql-code-generator - which is something that should be simple and valuable for success of the graphql ecosystem (and maybe some flutter stuff)

**Comment by wtrocki** [comment]
@sach97 I would suggest logging issue in graphql-code-generator as this might be specific to codegen rather than cli. As for the Graphback/templates client side queries, we have been using them with react native and flutter so capability is there
