### ISSUE TITLE
Does not work with hotel proxy local domain

### ISSUE THREAD

**Issue by pie6k** [Urigo/graphql-cli#235]
[Hotel](https://github.com/typicode/hotel) is amazing library allowing creating local domains when needed eg

`http://my-api.localhost`

After installing everything properly - `graphql get-schema` is still not working, while regular `curl` is working.

![image](https://user-images.githubusercontent.com/7311462/37240988-cd7d23e0-2452-11e8-9974-6d974214de3b.png)

**Comment by marktani** [comment]
How does your `.graphqlconfig.yml` look like?

**Comment by pie6k** [comment]
I have it in JSON format.

```
{
  "projects":{
    "XYZ":{
      "schemaPath":"src/schema/api.graphql",
      "extensions":{
        "endpoints": {
          "dev":"http://myapi.local/api/"
        },
        "prepare-binding": {
          "output": "src/schema/api.ts",
          "generator": "binding-ts"
        }
      }
    }
  }
}
```

**Comment by timshaw9791** [comment]
any progress?

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0`.
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new new alpha version channel for GraphQL CLI - `4.0.0-alpha.XXX` 

We've changed the `get-schema` command to use [GraphQL Code Generator](http://graphql-code-generator.com) plugin of GraphQL CLI with the Codegen's [`schema-ast` plugin](https://graphql-code-generator.com/docs/plugins/schema-ast). 

We've also moved to use the new `alpha` version of [`graphql-config`](https://medium.com/the-guild/graphql-config-708dd0e5d15f).

@pie6k @timshaw9791 @Soknath Could you check if that solves your issues?

Checkout new instructions in the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and let us know your feedback during that alpha period!

Feel free to contact us by opening a new issue or joining our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
