### ISSUE TITLE
graphql query: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by rngadam** [Urigo/graphql-cli#246]
server is postgraphile. get-schema and ping works. queries using graphcool work. command-line query using a file do not work.

```
> npm install -g graphql-cli
/usr/local/bin/graphql -> /usr/local/lib/node_modules/graphql-cli/dist/bin.js
/usr/local/bin/gql -> /usr/local/lib/node_modules/graphql-cli/dist/bin.js
+ graphql-cli@2.15.8
added 394 packages in 16.082s
> graphql init 
? Enter project name (Enter to skip): scryinfo
? Local schema file path: schema.graphql
? Endpoint URL (Enter to skip): http://localhost:3500/dbapi/graphql
? Name of this endpoint, for e.g. default, dev, prod: dev
? Subscription URL (Enter to skip): 
? Do you want to add other endpoints? No
? What format do you want to save your config in? JSON

About to write to /Users/rngadam/coderbunker/prj/scryinfo/dbnode/.graphqlconfig:

{
  "projects": {
    "scryinfo": {
      "schemaPath": "schema.graphql",
      "extensions": {
        "endpoints": {
          "dev": "http://localhost:3500/dbapi/graphql"
        }
      }
    }
  }
}
? Is this ok? Yes
> graphql get-schema -e dev -p scryinfo
project scryinfo - endpoint dev - Schema file was created: schema.graphql
> graphql -p scryinfo ping
Sending { __typename } query to http://localhost:3500/dbapi/graphql
✔ Call succeeded!
> graphql -p scryinfo query ./scenario1/query-route-toronto-vancouver.graphql 
✖ 
Cannot read property 'value' of undefined
> graphql -p scryinfo -e dev query ./scenario1/query-route-toronto-vancouver.graphql 
✖ 
Cannot read property 'value' of undefined
```

same query test ok and returns result in graphql playground.

<img width="1207" alt="screen shot 2018-03-28 at 10 08 24 am" src="https://user-images.githubusercontent.com/538542/38004715-1b90c05c-3270-11e8-88dc-78c58add49b3.png">

## node?

tested with these versions:

```
$ /usr/bin/env node --version
v9.6.1
$ /usr/bin/env node --version
v8.10.0
```

**Comment by schickling** [comment]
Thanks a lot for reporting this issue @rngadam. Can you please create a minimal repository to reproduce this problem?

**Comment by nzoschke** [comment]
I'm hitting this too.

```
$ cat q.graphql
{
  me {
    name
  }
}

$ npm start query q.graphql

> graphql-cli@0.0.0-semantic-release start /Users/noah/dev/graphql-cli
> ts-node src/bin.ts "query" "q.graphql"

✖
Cannot read property 'value' of undefined
```

 I did a bit of debugging and it's coming from `query.ts`:

```ts
  const document = parse(query)
  const operationNames = document.definitions.map(
    (d: OperationDefinitionNode) => d.name!.value,
  )
```

**Comment by nzoschke** [comment]
I don't get the error if I use an operation name like http://graphql.org/learn/queries/#operation-name

```graphql
query Me {
  me {
    name
  }
}
```

**Comment by schickling** [comment]
Seems indeed like a bug. Would anybody be up for creating a PR for this? 🙏

**Comment by schickling** [comment]
Hi @rajikaimal, unfortunately, I can just assign library maintainers but I'd be happy to merge a PR for this!

**Comment by tianhuil** [comment]
I have a proposed work-around here https://github.com/graphql-cli/graphql-cli/issues/381 but think we should make the error message more descriptive.

**Comment by chrisco314** [comment]
I am also hitting this - and also with a Postgraphile server from a trivial DB schema.  In my case, I hit it when trying to get the schema in JSON form.  It works with the default .graphql format, but not when trying to fetch in JSON.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version 4.0.0-alpha.0 . We don't have `query` command in our new alpha version. But if you have any suggestion to have it instead of having a playground, please feel free to open a new issue or create a PR. Also feel free to contact us using our Discord channnel.

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
