### ISSUE TITLE
 Example given in diff could be a bit confusing?

### ISSUE THREAD

**Issue by sean4wsome** [Urigo/graphql-cli#270]
The example we had in readme about usage of diff: 
> graphql diff -e dev -t prod  Show schema diff between "dev" and "prod" endpoints

gave me the impression that that is how our dev or prod endpoint should go, but i think it should be the opposite. 
The reason I say this because -e was passed in as oldschema  and -t as newschema to findBreakingChanges() from findbreakingchanges.js in graphql js
https://github.com/graphql/graphql-js/blob/master/src/utilities/findBreakingChanges.js
From the comment you can tell that it is about finding the breaking changes introduced by the newschema.
In daily development, isn't it often the case that we might introduce breaking changes to dev and we want to compare dev(the newschema) against prod(which is known to be good or the old schema?). 
Just want to raise this to discuss about this, thx.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use `diff` plugin of GraphQL CLI with GraphQL Inspector's diff commannd. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released new alpha versions channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We now use [GraphQL Inspector](https://graphql-inspector.com) as the default package for the `diff` command to track changes between schemas.

We believe GraphQL Inspector commands are also easier to use and more customizable, do you think it answers the need you specified above?

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during that alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
