### ISSUE TITLE
getProjectConfig() in context preparation should check error type

### ISSUE THREAD

**Issue by novemberborn** [Urigo/graphql-cli#273]
See these lines:

https://github.com/graphql-cli/graphql-cli/blob/d557f1028b1fa32ffbccd6612e56d2b2197ee9fd/src/index.ts#L71:L103

*Any* exception means the CLI tries to resolve the project. However `projectNames` defaults to an empty object, which is truthy, so it shows a prompt with nothing to pick from.

The error can come from `resolveEnvsInValues()`, in which case it should really be printed to the console. (Specifically I was getting this error because of #271.)

---

To me this is the core issue, but some other points (which probably should be their own issues):

* The `if (projectNames)` check doesn't work with the default `{}` value
* When not in a TTY, the CLI should exit with code 1 rather than prompt for user input

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI, which is a complete rewrite - `4.0.0-alpha.XXX`!

We've also moved to use the new `alpha` version of [`graphql-config`](https://medium.com/the-guild/graphql-config-708dd0e5d15f)!

Could you please check it out and see if your issue still persists?

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during the alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
