### ISSUE TITLE
CLI should fail with non-zero exit code

### ISSUE THREAD

**Issue by schickling** [Urigo/graphql-cli#286]
Right now the `graphql-cli` sometimes fails and doesn't return a non-zero exit code. This should be fixed in all possible cases to make it easier to use the CLI in (build) scripts.

**Comment by maartenvanvliet** [comment]
I am seeing this when running `graphql get-schema` against an endpoint that's not running.

**Comment by zdychacek** [comment]
This PR https://github.com/graphql-cli/graphql-cli/pull/364 adds emitting of an error instead of warning event when schema resolving fails, then exit process with non-zero exit code.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0`.
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new alpha version channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We've changed the `get-schema` command to use [GraphQL Code Generator](http://graphql-code-generator.com) plugin of GraphQL CLI with the Codegen's [`schema-ast` plugin](https://graphql-code-generator.com/docs/plugins/schema-ast). 

Checkout new instructions in the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and let us know your feedback during that alpha period!

@maartenvanvliet @zdychacek Could you check if that gives you the intended error?

Feel free to contact us by opening a new issue or joining our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
