### ISSUE TITLE
How to pass --insecure option?

### ISSUE THREAD

**Issue by thebetterjort** [Urigo/graphql-cli#287]
https://github.com/graphql-cli/graphql-cli/commit/d70d07868d8659dcd1da3ab6931e066559d38c29
```
graphql create graphed --insecure  --boilerplate react-fullstack-basic
```

Unknown arguments: insecure, boilerplate, graphed

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` 
Checkout new instructions and we will be happy to hear your feedback. 
Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We have just released a new structure for GraphQL CLI in new alpha versions `4.0.0-alpha.XXX`.

We suggest to use the `init` command of GraphQL CLI which was completely rewritten! 
Checkout the [new instructions](https://github.com/urigo/graphql-cli#usage--initialization) and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) on the docs and let us know your feedback. 

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
