### ISSUE TITLE
Diffing a local schema against a remote schema when the remote is newer

### ISSUE THREAD

**Issue by Caerbannog** [Urigo/graphql-cli#293]
The `diff` command currently supports two forms:
1. `graphql diff -e older -t newer` (this is related to issue #270)
2. `graphql diff -e older`, which assumes the local schema is more recent than `older`.

Form number 1 allows swapping `older` and `newer`.
It would be convenient to do the same with form number 2 in those cases:
- You want to find the breaking changes if the remote schema were to replace the local schema.
- You want to display the reverse of the diff.

Use case: the local `schema.json` is version controlled in an apollo-android or apollo-ios repository.

Maybe we can add a third form `graphql diff -t newer` ?

**Comment by Caerbannog** [comment]
It might also be useful to diff two local schemas.

**Comment by xzyfer** [comment]
@schickling are you open to a PR for this feature?

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use `diff` plugin of GraphQL CLI with GraphQL Inspector's diff commannd. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released new alpha versions channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We now use [GraphQL Inspector](https://graphql-inspector.com) as the default package for the `diff` command to track changes between schemas, which is highly customizable.

Do you think that this requirement is still necessary when using GraphQL Inspector?

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during that alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
