### ISSUE TITLE
command prepare both exists in plugin

### ISSUE THREAD

**Issue by FredyC** [Urigo/graphql-cli#302]
Full warning is like this. It's strange warning considering that `graphql-cli-prepare` is a dependency of `graphql-cli`

> warning command prepare both exists in plugin D:\workspace\app\node_modules\graphql-cli-prepare and is shipped with the graphql-cli.

_graphql-cli@2.16.0_

**Comment by parweb** [comment]
#metoo

**Comment by Kisepro** [comment]
same
It seems to break the **grapqhql prepare**

**Comment by peterschussheim** [comment]
another one here...

**Comment by divyenduz** [comment]
We deployed a [release today](https://github.com/graphql-cli/graphql-cli/releases/tag/v2.16.1) that makes `graphql codegen` more robust. 

Please install the new cli via `npm install -g graphql-cli` and try the `graphql codegen` command. 

Note that with `prisma-binding` 1.x, we need to use `graphql prepare`
and with `prisma-binding` 2.x, we need to use `graphql codegen`

[Documentation for codegen](https://www.prisma.io/docs/reference/prisma-bindings/code-generation-cosha9rah3).

Thanks! 

P.S. This warning might still appear but that is not breaking `graphql codegen`, there were other issues which are resolved.

**Comment by Kisepro** [comment]
@divyenduz Not working for me but at least I have an error message now 

> graphql codegen
> warning command prepare both exists in plugin C:\Project\myBjjGit\project\serv\node_modules\graphql-cli-prepare and is shipped with the graphql-cli.
> The plugin is being ignored.
> × Generating bindings for project database...
> { Error: Cannot find module 'typescript'
>     at Function.Module._resolveFilename (module.js:542:15)
>     at Function.Module._load (module.js:472:25)
>     at Module.require (module.js:585:17)
>     at require (internal/module.js:11:18)
>     at Object.register (C:\Project\myBjjGit\project\serv\node_modules\ts-node\src\index.ts:207:25)
>     at C:\Project\myBjjGit\project\serv\node_modules\prisma-binding\src\bin.ts:52:24
>     at step (C:\Project\myBjjGit\project\serv\node_modules\prisma-binding\dist\bin.js:33:23)
>     at Object.next (C:\Project\myBjjGit\project\serv\node_modules\prisma-binding\dist\bin.js:14:53)
>     at C:\Project\myBjjGit\project\serv\node_modules\prisma-binding\dist\bin.js:8:71
>     at new Promise (<anonymous>) code: 'MODULE_NOT_FOUND' }
> 
> 
> C:\Project\myBjjGit\project\serv>npm list -g typescript
> C:\Users\ancu\AppData\Roaming\npm
> +-- graphcool@0.10.1
> | `-- graphcool-cli-core@1.8.0
> |   `-- typescript@2.6.2
> +-- graphcool-framework@0.11.5
> | `-- graphcool-cli-core@1.10.7-framework
> |   `-- typescript@2.6.2
> `-- typescript@2.9.1

As you can see it's asking for "typescript" but I have the package

**Comment by divyenduz** [comment]
Did you already try to remove `node_modules`, reinstall and try again?

Are you on Windows 10 server? Can you please answer the following questions:-

1. Your `prisma.yml` file

1. Your graphql config file (some thing like `.graphqlconfig.yml`)

1. Your prisma cli version via `prisma --version`

1. Details about the OS

Thanks

**Comment by Kisepro** [comment]
@divyenduz 

I managed to make it working.  I explicitly installed the "typescript" package in my project with the classical  :   

`npm install --save typescript`

Is it a bug or should I always install it locally for each project ?

**Comment by divyenduz** [comment]
@Kisepro: Thanks for the details, it should have worked with global installation as well. This is indeed a bug on windows. Can you please [create a separate issue](https://github.com/graphql-cli/graphql-cli/issues/new) for this?

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` .
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

This was a complete rewrite.

We use [GraphQL Code Generator](http://graphql-code-generator.com) as the default package for the `codegen` command to generate typings and code from schema using it's various plugins.

We've also moved to use the new `alpha` version of [`graphql-config`](https://medium.com/the-guild/graphql-config-708dd0e5d15f)!

There is no need for the `prepare` plugin and command anymore as with the new `config` you can merge together schemas from any sources, single or multiple!

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during the alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
