### ISSUE TITLE
Add option to return with non-zero exit code if diff finds breaking/dangerous changes

### ISSUE THREAD

**Issue by fabsrc** [Urigo/graphql-cli#304]
Right now the `diff` command only prints out the schema diff and points out breaking/dangerous changes. It would be cool if there was an option like `--fail-on-breaking-changes`/`--fail-on-dangerous-changes` to make the tool return with a non-zero exit code. This would be particularly useful in a CI job that compares the schema with the prod environment and should fail if there are any breaking changes.

 I'm currently using a bash script to achieve this:

```sh
#!/usr/bin/env bash

npm i -g graphql-cli
DIFF=$(graphql diff -e $1 -t $2)
echo "$DIFF"

if [[ $DIFF = *"BREAKING CHANGES"* ]]
then
  exit 1
fi
```

However I think it makes sense to implement this feature into the tool.

**Comment by redreceipt** [comment]
Yep! The major upside here is including a breaking change check in a CI. I'll be using a script to do the same but would be nice to be built into the `diff` command.

**Comment by fabsrc** [comment]
@redreceipt I ended up creating a dedicated tool for this. You can check it out here: https://github.com/fabsrc/graphql-schema-diff

**Comment by redreceipt** [comment]
@fabsrc excellent! Thank you!

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use `diff` plugin of GraphQL CLI with GraphQL Inspector's diff commannd. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released new alpha versions channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We use [GraphQL Inspector](https://graphql-inspector.com) as the default package for the `diff` command to track changes between schemas which is highly configurable for specifying what is considered a breaking change.

@fabsrc your tool looks great!  would you like to collaborate with us on [GraphQL Inspector](https://github.com/kamilkisiela/graphql-inspector)? 

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during that alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
