### ISSUE TITLE
Allow endpoint urls in the diff command

### ISSUE THREAD

**Issue by fabsrc** [Urigo/graphql-cli#305]
The `diff` command currently only supports endpoint names, which means that in order to diff two schemas a `.graphqlconfig` file has to exist and all GraphQL endpoints have to be declared in it. To increase flexibility I suggest to also allow endpoint urls in the `diff` command, e.g.:

```bash
$ graphql diff -e https://graphql.org/swapi-graphql -t https://myownserver.com/swapi-graphql
```

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use `diff` plugin of GraphQL CLI with GraphQL Inspector's diff commannd. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released new alpha versions channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We now use [GraphQL Inspector](https://graphql-inspector.com) as the default package for the `diff` command to track changes between schemas.
It can handle schemas from any type of sources specified with the new [`graphql-config`](https://medium.com/the-guild/graphql-config-708dd0e5d15f)!

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during that alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
