### ISSUE TITLE
Cannot get-schema when No project defined

### ISSUE THREAD

**Issue by rwinzhang** [Urigo/graphql-cli#327]
my .graphqlconfig file
```
{
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "production": {
        "url": "https://api.github.com/graphql",
        "headers": {
          "Authorization": "Bearer ${env:API_TOKEN}"
        }
      }
    }
  }
}
```

current workaround is running this command 
`API_TOKEN=abc graphql get-schema --project github`

**expected behavior**
the following command should run
`API_TOKEN=abc graphql get-schema`

**Comment by tanduong** [comment]
I ran into the same issue. The project can be specified like this:

```
{
  "projects": {
    "Project Name": {
      "schemaPath": "schema.graphql",
      "extensions": {
        "endpoints": {
          "dev":  {
            "url": "http://localhost:3000/graphql",
            "headers": {
              "Authorization": "Bearer ${env:AUTH_TOKEN_ENV}"
            }
          }
        }
      }
    }
  }
}
```

**Comment by macrozone** [comment]
same problem here.  get-schema should also work, when no project is specified, in particular, because in `graphql init` it defaults to no project.

Also, if you add a project to your graphqlconfig, every other `graphql` command will ask you to select a project (which is only one).

**Comment by leethree** [comment]
This is clearly a bug. all the commands should work even if no project is specified.

**Comment by dev-rkoshlyak** [comment]
```
graphql init
graphql get-schema -e dev
```
This commands works for me, note if you put -e dev, in the end, it will work

**Comment by DanielRuf** [comment]
Still the same, this is a bug and should be fixed.
Does anybody know where the bug is in the code?

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use GraphQL Code Generator plugin of GraphQL CLI with Codegen's `schema-ast` plugin. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
