### ISSUE TITLE
Renaming .graphqlconfig values induce crash of graphql codegen

### ISSUE THREAD

**Issue by Sharlaan** [Urigo/graphql-cli#335]
[Original issue](https://github.com/prismagraphql/prisma/issues/2802)

**Comment by Sharlaan** [comment]
Also i think api.ts is not exposing correct generated types, but i'm not sure i'm still new at GraphQL.

For example if i have in app.schema.graphql the following type :
 ```yaml
type Query {
  order(id: ID!): Order
}
```

i find this in api.ts (renaming path back to `src/generated/prisma.graphql` for database project)
```yaml
export interface Query {
    order: <T = Order | null>(args: { where: OrderWhereUniqueInput }, info?: GraphQLResolveInfo | string, options?: Options) => Promise<T> ,
    ...
}
```  
and in `database.ts`:
```yaml
export interface Query {
    order: <T = Order | null>(args: { where: OrderWhereUniqueInput }, info?: GraphQLResolveInfo | string, options?: Options) => Promise<T> ,
    ...
}
```

Looks like the api.ts Query interface is wrong generated, apparently based on prisma.gql instead of app.schema.gql ?

**Comment by divyenduz** [comment]
Can you share your `database.yml` file. Most likely it is a typo at your end as the error from original report is `{ Error: ENOENT: no such file or directory, open 'D:\Mes Projets\graphql-shop\api\src\generated\prisma.graphql'`

but the name for db schema in graphql config is `database.schema.graphql`

**Comment by Sharlaan** [comment]
```
yml
```# endpoint: <PRISMA_ENDPOINT>/[<workspace>/]<service>/<stage>
endpoint: ${env:PRISMA_PROTOCOL}://${env:PRISMA_HOST}:${env:PRISMA_PORT}/${env:PRISMA_SERVICE}/${env:PRISMA_STAGE}
# endpoint: ${env:PRISMA_ENDPOINT}

# to disable authentication:
# disableAuth: true
secret: ${env:PRISMA_SECRET}

# the file path pointing to your data model
datamodel: datamodel.graphql

# seed your service with initial data based on seed.graphql
seed:
  import: seed.graphql

# Download the GraphQL schema of the Prisma API into
# `src/generated/prisma.graphql` (as specfied in `.graphqlconfig.yml`).
# Then generate the corresponding TypeScript definitions into
# `src/generated/prisma.ts` (also specfied in `.graphqlconfig.yml`)
# with `graphql codegen` .
hooks:
  post-deploy:
    - graphql get-schema --project database
    - graphql codegen

**Comment by divyenduz** [comment]
Thanks! also, the codegen part in `app` project in your `.graphqlconfig.yml` looks unwanted. Can you please tell me the reason why you used that? 

Also, this does not explain the error message about `prisma.graphql` from my previous comment. 

Can you provide a minimal reproduction for this issue? Thanks!

**Comment by divyenduz** [comment]
@Sharlaan : So, you mean, that renaming `prisma.graphql` to anything other than `prisma.graphql` does not work?

**Comment by Sharlaan** [comment]
exact

**Comment by Sharlaan** [comment]
By the way, i also tried to get correct resolver typings with replacing, in app project, the generator `prisma-binding` with `graphql-binding`, but then it asks for some .ts file ... i'm confused.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` .
We use GraphQL Code Generator for `codegen` command to generate typings and code from schema using various plugins of it.
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We use [GraphQL Code Generator](http://graphql-code-generator.com) as the default package for the `codegen` command to generate typings and code from schema using it's various plugins.

We've also moved to use the new `alpha` version of [`graphql-config`](https://medium.com/the-guild/graphql-config-708dd0e5d15f)!

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback. 

You can still change the default package for `codegen` from GraphQL Code Generator to Apollo's codegen.
If you want to keep using Apollo codegen and don't know how to do that, please open a new issue so we can track it and make sure it works and that it's documented properly.

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
