### ISSUE TITLE
[codegen/flow] Export `interface Prisma` in generated Flow for Prisma

### ISSUE THREAD

**Issue by morajabi** [Urigo/graphql-cli#336]
![image](https://user-images.githubusercontent.com/12202757/43261414-d701fa24-90f1-11e8-9b30-9200aafe99d4.png)

We're exporting `Query`, `Mutation`, etc individually. Exporting the whole Prisma interface would be very useful for getting auto-completion! 

Currently, as a workaround, I have to keep a version of `interface Prisma` myself in my code.

It should require much changes, would like to help to land this :)

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` .
We use GraphQL Code Generator for `codegen` command to generate typings and code from schema using various plugins of it.
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We use [GraphQL Code Generator](http://graphql-code-generator.com) as the default package for the `codegen` command to generate typings and code from schema using it's various plugins.

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback. 

You can still change the default package for `codegen` from GraphQL Code Generator to Apollo's codegen.
If you want to keep using Apollo codegen and don't know how to do that, please open a new issue so we can track it and make sure it works and that it's documented properly.

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
