### ISSUE TITLE
Extend codegen to emit type resolver for interfaces extending Node

### ISSUE THREAD

**Issue by avkonst** [Urigo/graphql-cli#338]
I have built this template project: https://github.com/graphql-boilerplates/typescript-graphql-server/tree/master/advanced

After bootstrap I got the file: src/generated/prisma.ts with 2 interfaces implementing Node:
```typescript
export interface Post extends Node {
  id: ID_Output
  createdAt: DateTime
  updatedAt: DateTime
  isPublished: Boolean
  title: String
  text: String
  author: User
}

export interface User extends Node {
  id: ID_Output
  email: String
  password: String
  name: String
  posts?: Post[]
}
```

Running `yarn dev` prints the warning:
```
Type "Node" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
```

I have implemented type resolution for the apollo server and the warning is gone now:
```typescript
import { Post, User } from '../generated/prisma';

export const Node = {
    // tslint:disable-next-line:function-name
    __resolveType(obj: any, context: Context, info: any) {
        if ((obj as Post).author) {
            return 'Post';
        }
        if ((obj as User).email) {
            return 'User';
        }
        return null;
    },
};
```

This implementation is useful not only for Apollo resolver itself, but it is also useful in general within the resolvers and other routines processing instances of data.

However, I see this implementation will be a point of trouble every time when new classes are added to the schema. This function needs to be updated accordingly. Moreover, manual implementation based on checking of property existence is reliable while the number of classes is small and there are clearly unique identifiable properties to use.

Instead of manual implementation of this function, I suggest the code generator could emit `type resolution` function for all interfaces extending `Node`. The implementation should assume that every interface has got unique combination of properties and should use just enough subset of properties in order to identify interface of an instance reliably. The case of complete duplication of a set of properties from 2 different interfaces would suggest it is an error in the initial schema design, which is also a good thing to catch.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` .
We use GraphQL Code Generator for `codegen` command to generate typings and code from schema using various plugins of it.
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We use [GraphQL Code Generator](http://graphql-code-generator.com) as the default package for the `codegen` command to generate typings and code from schema using it's various plugins.

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback. 

You can still change the default package for `codegen` from GraphQL Code Generator to Apollo's codegen.
If you want to keep using Apollo codegen and don't know how to do that, please open a new issue so we can track it and make sure it works and that it's documented properly.

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
