### ISSUE TITLE
Running graphql get-schema project_name gives an error, because of incorrect relative path of prisma.yml

### ISSUE THREAD

**Issue by artem-korolev** [Urigo/graphql-cli#340]
**Describe the bug**
Running graphql-cli tools have issue. It does not take into account in which directory .graphqlconfig file is placed. I think that paths in .graphqlconfig file should be relative to config file itself (or absolute if they are absolute). right now paths are relative to the directory you run graphql-cli tools, not to .graphqlconfig.

**To Reproduce**
1. Create this directory scructure
- workspace
   .graphqlconfig
   - servers
   --- prisma
   --- app
   --- admin
   - clients
   --- relay-native
   --- react-graphql

2. **.graphqlconfig**:
```json
{
	"projects": {
		"graphql": {
			"schemaPath": "servers/app/src/generated/prisma.graphql",
			"extensions": {
				"prisma": "servers/prisma/prisma.yml"
			}
		}
	}
}
```

3. install prisma to workspace/servers/prisma

4. install yoga client in servers/app

5. run this:
```bash
cd servers/app
graphql get-schema -p graphql
× servers/prisma/prisma.yml could not be found.
```
6. Not let me show you how to fix this issue with current implementation of graphql-cli tools
if I update my config with this line:
"prisma": "../../servers/prisma/prisma.yml"
everything works okay then.
So I guess its a bug, that should be fixed

I want to have at least 2 applications for one prisma server.. its usually 1) app 2) admin... pretty logical.. different endpoints.. different auth rules, security flows and so on.
and I want auto update schemas in all applications when I change prisma schema... current approach support updating only one app.. well.. maybe i'm wrong.. this type of project structure looks to me pretty logical, but i'm not able to configure it properly for some reason

**Comment by marktani** [comment]
To me, it's difficult to understand your exact situation. Could you please share a reproduction according to [this bug report template](https://github.com/graphql-cli/graphql-cli/issues/new?template=bug_report.md)? This would help me a lot.

Also, I have difficulties to read your issue report, due to its punctuation and general format. If you would improve that, it would help me as well.

Thanks!

**Comment by liujiaqi** [comment]
I think so, path in a config file should relative to the config file itself, not your work directory.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use GraphQL Code Generator plugin of GraphQL CLI with Codegen's `schema-ast` or `introspection` plugin. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new alpha version channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We've changed the `get-schema` command to use [GraphQL Code Generator](http://graphql-code-generator.com) plugin of GraphQL CLI with the Codegen's [`schema-ast` plugin](https://graphql-code-generator.com/docs/plugins/schema-ast). 

We've also moved to use the new `alpha` version of [`graphql-config`](https://medium.com/the-guild/graphql-config-708dd0e5d15f) which has been rewritten with env variables support etc.

Checkout new instructions in the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and let us know your feedback during that alpha period!

Could you check if that solves your issues when using it with the Prisma config?

Feel free to contact us by opening a new issue or joining our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
