### ISSUE TITLE
graphql-cli fails npm audit

### ISSUE THREAD

**Issue by rsnay** [Urigo/graphql-cli#342]
**Describe the bug**
Running `npm audit` on a project with `graphql-cli 2.16.5` fails. Three vulnerabilities are reported, and one of them, `adm-zip`, can be patched by upgrading `adm-zip` to `>= 0.4.9`.

`0.4.7` is currently used in graphql-cli, as of this pull request in May: [https://github.com/graphql-cli/graphql-cli/pull/289](https://github.com/graphql-cli/graphql-cli/pull/289)

**To Reproduce**
1. `mkdir graphql-cli-test`
2. `cd graphql-cli-test/`
3. `npm init -y`
4. `npm install graphql-cli`
5. `npm audit`

**Expected behavior**
While 2 of the 3 reported vulnerabilities have no patch currently available, when a patch is available the dependency should be upgraded and bugs resolved (https://github.com/graphql-cli/graphql-cli/issues/277 seems to be why `adm-zip` was kept at `0.4.7`)

**Screenshots**
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Write via Archive Extraction                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ adm-zip                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.4.9                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ graphql-cli                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ graphql-cli > adm-zip                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/681                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Versions**
 - OS: `Amazon Linux 2 AMI`
 - `graphql-cli`: `2.16.5`

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` 
Checkout new instructions and we will be happy to hear your feedback. 
Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We have just released a new structure for GraphQL CLI in new alpha versions `4.0.0-alpha.XXX`!

We suggest to use the `init` command of GraphQL CLI which was completely rewritten! 
Checkout the [new instructions](https://github.com/urigo/graphql-cli#usage--initialization) and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) on the docs and let us know your feedback. 

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
