### ISSUE TITLE
deprecated apollo-codegen@0.19.1

### ISSUE THREAD

**Issue by ysantalla** [Urigo/graphql-cli#348]
npm WARN deprecated apollo-codegen@0.19.1: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-generation for more information.

 - OS: Ubuntu 18.04
 -graphql-cli: 2.16.7
 - other packages if applicable

**Comment by zefexdeveloper** [comment]
The same happening here.

**Comment by berstend** [comment]
Unfortunately the new apollo cli seems to be a different beast altogether (e.g. `.graphqlconfig` support has been removed). :-/

**Comment by tianhuil** [comment]
Would love to see this fixed.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` .
We use GraphQL Code Generator for `codegen` command to generate typings and code from schema using various plugins of it.
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH
