### ISSUE TITLE
configurations and help

### ISSUE THREAD

**Issue by GlauberF** [Urigo/graphql-cli#349]
**change app namecha**

How can I change the name of the app (graphql app)?
![deepin screenshot_selecionar area_20181004005731](https://user-images.githubusercontent.com/11314585/46452217-f70eb180-c770-11e8-9b4b-11acaf4bcc84.png)

in the background (```graphql playground```), in order to close the browser and not fetch the connection

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` 
Checkout new instructions and we will be happy to hear your feedback. 
Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by wtrocki** [comment]
@GlauberF Thank you so much for the logging issue. Our templates now changed and the following element is no longer visible
