### ISSUE TITLE
get-schema --json fails with "Cannot read property 'types' of undefined"

### ISSUE THREAD

**Issue by terkiterje** [Urigo/graphql-cli#376]
**Describe the bug**
The documentation from get-schema --help lists 
```
  --json, -j      Output as JSON                                       [boolean]
```
When using the --json option for get-schema with version 3.0.3, it always fails with the same error "Cannot read property 'types' of undefined"

**To Reproduce**
```shell
yarn run gql get-schema --json --endpoint https://graphql.brandfolder.com/graphql --output schema.json
```

Here I randomly selected the first public endpoint I could find from google search "public graphql endpoint", since the problem seems to be unrelated to the endpoint.

**Expected behavior**
A schema.json to be created without errors, like in version 2.16.0

**Versions:**
 - `graphql-cli`: [`3.0.3`]

**Additional context**
The works with 2.16.0 version. A possible mitigation seems to be just dropping --json since the schema contains the JSON needed (but this also includes other unwanted stuff in the schema, I guess)

**Comment by enisdenjo** [comment]
I have the same issue.

**Comment by mislavlukach** [comment]
I can confirm this is still an issue.
Ommiting the --json flag still works great though.

Working : `graphql get-schema --endpoint http://localhost:3000/graphql  --output schema.graphql`

Not working: `graphql get-schema --json --endpoint http://localhost:3000/graphql  --output schema.json`

**Comment by joeynimu** [comment]
I am having the same issue, any fixes for this?

**Comment by joeynimu** [comment]
@mislavlukach omitting the `json` flag worked for me while ensuring that the file name (output flag) has a json extension.
e.g `graphql get-schema --endpoint="https://yourendpoint.dev/graphiql" --output="schema.json"`

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use GraphQL Code Generator plugin of GraphQL CLI with Codegen's `schema-ast` or `introspection` plugin. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new alpha version channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We've changed the `get-schema` command to use [GraphQL Code Generator](http://graphql-code-generator.com) plugin of GraphQL CLI with the Codegen's [`schema-ast` plugin](https://graphql-code-generator.com/docs/plugins/schema-ast). 

Checkout new instructions in the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and let us know your feedback during that alpha period!

Could you check if that runs as intended?

Feel free to contact us by opening a new issue or joining our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
