### ISSUE TITLE
graphql create my-app --boilerplate react-fullstack-advanced

### ISSUE THREAD

**Issue by osmannassar2019** [Urigo/graphql-cli#392]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. `Windows 10`, `OS X High Sierra`, `Ubuntu 16.04`] 
 - `graphql-cli`: [e.g. `2.16.5`]
 - other packages if applicable

**Additional context**

**Comment by gius80** [comment]
Same issue here.
"Choose GraphQL boilerplate project:" doesn't list "react-fullstack-advanced.

**Versions**
- OS: Max OS 10.14.2
- graphql-cli: 3.0.9

**Comment by wangkailang** [comment]
[boilerplates template](https://github.com/graphql-cli/graphql-cli/blob/master/src/cmds/create/boilerplates.ts) can not find `react-fullstack-advanced`

**Comment by wdoug** [comment]
It was deleted in [this commit](https://github.com/graphql-cli/graphql-cli/commit/bfe7eeade74c2883cc6b162cf62bcd346d279d28#diff-4cbc817bc362166e981aa3bf1b8a6573). The question is why though. I don't see an explanation. @nikolasburk would you mind commenting on why this was removed?

**Comment by MMayla** [comment]
Is there any update regarding this? as @wdoug mentioned it's removed, is it removed by mistake, or it doesn't work anymore?

Thanks for creating this

**Comment by Timonzimm** [comment]
Any update or solution found?

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use `init` command of GraphQL CLI with Graphback. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We have just released a new structure for GraphQL CLI in a new alpha versions track -  `4.0.0-alpha.XXX`!!

We suggest to use the `init` command of GraphQL CLI which was completely rewritten! 

Checkout the [new instructions](https://github.com/urigo/graphql-cli#usage--initialization) and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) on the docs and let us know your feedback. 

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
