### ISSUE TITLE
I can't install react-fullstack-graphql/advanced/ Using Graphql-cli My system is ubuntu 16.04  Please Help me

### ISSUE THREAD

**Issue by osmannassar2019** [Urigo/graphql-cli#393]
I can't install react-fullstack-graphql/advanced/ Using Graphql-cli
My system is ubuntu 16.04

Please Help me

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use `init` command of GraphQL CLI with Graphback. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
