### ISSUE TITLE
Issue with graphql create

### ISSUE THREAD

**Issue by samburgers** [Urigo/graphql-cli#396]
**Describe the bug**
Generated boilerplate for `typescript-graphql-server` ruins application folder structure and flattens all files to the root folder. [discussed here](https://github.com/graphql-boilerplates/typescript-graphql-server/issues/410) and decided it is an issue with `graphql create`

**To Reproduce**
```bash
graphql create my-app --boilerplate typescript-advanced
```

**Expected behavior**
Generated application files should retain the folders and paths described in the [typescript-graphql-server](https://github.com/graphql-boilerplates/typescript-graphql-server).

**Screenshots**
<img width="329" alt="screen shot 2019-01-16 at 8 55 46 pm" src="https://user-images.githubusercontent.com/1476939/51241086-3041f900-19d1-11e9-92f1-a8ca81e42455.png">

**Versions (please complete the following information):**
 - OS: [`OS X High Sierra`] 
 - `"graphql-cli@3.0.4"`

**Additional context**
Appears to be related to the `graphql create` command, as [discussed here](https://github.com/graphql-boilerplates/typescript-graphql-server/issues/410)

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` . 
We now have `init` command instead that uses Graphback behind the scene.
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We have just released a new structure for GraphQL CLI in a new alpha versions track -  `4.0.0-alpha.XXX`!

We suggest to use the `init` command of GraphQL CLI which was completely rewritten! 

Checkout the [new instructions](https://github.com/urigo/graphql-cli#usage--initialization) and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) on the docs and let us know your feedback. 

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
