### ISSUE TITLE
[macOS] graphql create doesn't work properly for folder names composed of numbers

### ISSUE THREAD

**Issue by nakhodkiin** [Urigo/graphql-cli#397]
CLI command `$ graphql create 777` results in an error `directory.match is not a function`
but if I try to append a slash to the folder name like e.g.`$ graphql create 999/` it works properly.

<img width="822" alt="screen shot 2019-01-16 at 5 57 25 pm" src="https://user-images.githubusercontent.com/14351638/51261161-645cf000-19b8-11e9-8860-9e06f9158da4.png">

*trivial*
In a case when command eventually executes, I'm prompted with a dialog with a bunch of options to choose from and I hit `Ctrl+C` to terminate the process, but empty folder is created anyway.

**Versions (please complete the following information):**
 - OS: `macOS Mojave Version 10.14.2` 
 - Version of `graphql-cli`: `3.0.4`
- Shell: `Oh My ZSH!`

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use `init` command of GraphQL CLI with Graphback. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
