### ISSUE TITLE
Broken graphql-cli install

### ISSUE THREAD

**Issue by gitxav** [Urigo/graphql-cli#404]
**Describe the bug**

graphql-cli 'create' command does not generate the right directory structure for new projects. In fact it mixes files in a single root folder.
In addition, it doesn't prompts for any cluster configuration as 'prisma deploy' command does for example.

**To Reproduce**
$ npm install -g graphql-cli
$ graphql create app & cd app
$ npm i

**Expected behavior**
Well-formed generated boilerplate

**Screenshots**

![screenshot from 2019-01-21 11-42-11](https://user-images.githubusercontent.com/11687381/51504167-26d7d880-1da5-11e9-84a3-6fc5639f7d3a.png)

**Versions**
 - OS: `Ubuntu 16.04`
 - `graphql-cli`: `3.0.5`
 - node v10.15.0 and npm v6.6.0

**Additional context**

The graphql-cli install throws peer dependency warnings itself:

npm WARN graphql-import@0.4.5 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-codegen-core@0.20.1 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-static-binding@0.9.3 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN @kbrandwijk/swagger-to-graphql@2.4.3 requires a peer of graphql@^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

The generated app complains too:

warning " > graphql-boilerplate-install@0.1.9" has unmet peer dependency "prisma@1.3.2".

Thanks in advance.

**Comment by ZiQiLN** [comment]
Have you tried to update whole dependecies by `yarn upgrade`?

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` . Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
