### ISSUE TITLE
Need to update apollo-codegen-core

### ISSUE THREAD

**Issue by shinokada** [Urigo/graphql-cli#422]
**Intended outcome:**

There should be no error message when I run `npm ls -g --depth=0`.

**Actual outcome:**

```
node -v
v10.13.0
npm ls -g --depth=0
/Users/mynamehere/.nvm/versions/node/v10.13.0/lib
├── eslint@5.13.0
├── graphql-cli@3.0.9
├── now@13.1.3
├── npm@6.7.0
└── prisma@1.26.4

npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by apollo-codegen-core@0.20.1
npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by apollo-codegen-core@0.20.1
npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by apollo-codegen-core@0.20.1
npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by apollo-codegen-core@0.20.1
npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by apollo-codegen-core@0.20.1
npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by apollo-codegen-core@0.20.1
npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by apollo-codegen-core@0.20.1
npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by graphql-import@0.4.5
npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by graphql-static-binding@0.9.3
npm ERR! peer dep missing: graphql@^0.12.0 || ^0.13.0, required by @kbrandwijk/swagger-to-graphql@2.4.3
```

**Versions**

```
├── eslint@5.13.0
├── graphql-cli@3.0.9
├── now@13.1.3
├── npm@6.7.0
└── prisma@1.26.4
```

Current version of `apollo-codgen-core` is v0.32.5 and `graphql-cli` is using 0.20.1.
Is it possible to upgrade to the current version?

**Comment by stevensacks** [comment]
I am getting this error, as well.

I'm aware that it says
```
deprecated apollo-codegen@0.20.2: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-generation for more information.
```

But apollo's version of graph-cli's `get-schema` is not the same and does not work for my purposes.

**Comment by digeomel** [comment]
Any updates on this?

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` .
We use GraphQL Code Generator for `codegen` command to generate typings and code from schema using various plugins of it.
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We have just released a new structure for GraphQL CLI in new alpha versions track -  `4.0.0-alpha.XXX`!

We use [GraphQL Code Generator](http://graphql-code-generator.com) as the default package for the `codegen` command to generate typings and code from schema using it's various plugins.
Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback. 

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

You can still change the default package for `codegen` from GraphQL Code Generator to Apollo's codegen.
If you want to keep using Apollo codegen and don't know how to do that, please open a new issue so we can track it and make sure it works and that it's documented properly.

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
