### ISSUE TITLE
[Proposal] GraphQL CLI logo

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [Urigo/graphql-cli#430]
Here is my idea:

![graphql-cli-logo-prefinal](https://user-images.githubusercontent.com/7892779/52916538-dc893f00-32f1-11e9-9596-ded208962226.png)

Need a little polishing. License: CC BY-SA. :wink:

@kuldar PTAL.

**Comment by kuldar** [comment]
Thanks so much for the submission @FluorescentHallucinogen! 

I really like the logo idea. I played around with it to scale it in different sizes and ended up adjusting the line weights a bit to unify the feel.

What do you think about this slight iteration?

<img width="849" alt="comparison" src="https://user-images.githubusercontent.com/1710629/53043710-5bfd4680-3489-11e9-9cef-5502656483a9.png">

![graphqlcli](https://user-images.githubusercontent.com/1710629/53043632-31ab8900-3489-11e9-8ee2-f66da52fd665.png)

**Comment by FluorescentHallucinogen** [comment]
@kuldar 
> What do you think about this slight iteration?

LGTM. :+1:

**Comment by kuldar** [comment]
Awesome, I added the logo to README! 👍 

For other usages, here's also the SVG source and a fairly large PNG.

```svg
<svg width="114" height="128" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M58.39 124.176L3.559 92.518l2.84-4.92 54.832 31.658-2.841 4.92z" fill="#E10098"/>
  <path d="M57.423 121.771l-2.482-4.298 47.689-27.534 2.481 4.298-47.688 27.534z" fill="#E10098"/>
  <path d="M101.017 32.958h5.682v63.316h-5.682V32.958zM5.736 32.958h5.681v63.316h-5.68V32.958z" fill="#E10098"/>
  <path d="M106.022 41.667L51.19 10.01l2.841-4.92 54.831 31.657-2.84 4.92z" fill="#E10098"/>
  <path d="M6.414 41.645l-2.84-4.92L58.405 5.069l2.84 4.92-54.83 31.657z" fill="#E10098"/>
  <path d="M18.525 42.18c-2.729 4.83-8.813 6.479-13.561 3.702-4.748-2.776-6.368-8.965-3.64-13.795 2.73-4.83 8.814-6.478 13.562-3.702 4.748 2.805 6.369 8.966 3.64 13.795zM1.325 95.913c-2.73-4.83-1.109-10.99 3.639-13.795 4.748-2.777 10.804-1.128 13.561 3.702 2.73 4.83 1.11 10.99-3.639 13.795-4.776 2.776-10.832 1.128-13.561-3.702zM56.642 128a10.087 10.087 0 0 1-10.097-10.096 10.087 10.087 0 0 1 10.097-10.097 10.087 10.087 0 0 1 10.096 10.097c0 5.554-4.513 10.096-10.096 10.096zM111.918 95.913c-2.774 4.83-8.957 6.478-13.782 3.702-4.825-2.776-6.472-8.966-3.699-13.795 2.774-4.83 8.957-6.479 13.782-3.702 4.855 2.805 6.501 8.965 3.699 13.795zM94.439 42.18c-2.777-4.83-1.128-10.99 3.702-13.795 4.829-2.776 10.989-1.128 13.795 3.702 2.776 4.83 1.128 10.99-3.702 13.795-4.83 2.777-11.019 1.128-13.795-3.702zM56.642 20.192a10.087 10.087 0 0 1-10.097-10.096A10.087 10.087 0 0 1 56.642 0a10.087 10.087 0 0 1 10.096 10.096 10.087 10.087 0 0 1-10.096 10.096z" fill="#E10098"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M34.483 44.248a3.422 3.422 0 0 1 4.838-.121l15.536 14.777a3.422 3.422 0 0 1 0 4.96L39.32 78.642a3.422 3.422 0 1 1-4.717-4.96l12.928-12.298-12.928-12.298a3.422 3.422 0 0 1-.121-4.838zM48.342 79.682a3.422 3.422 0 0 1 3.423-3.422h23.871a3.422 3.422 0 0 1 0 6.845H51.765a3.422 3.422 0 0 1-3.423-3.423z" fill="#E10098"/>
</svg>
```

![gqlcli](https://user-images.githubusercontent.com/1710629/53046265-f52f5b80-348f-11e9-9973-9009fa740211.png)

**Comment by FluorescentHallucinogen** [comment]
@kuldar Could you please set it as GitHub organization logo?

**Comment by kuldar** [comment]
@FluorescentHallucinogen I don't have permissions myself, but I asked Johannes to update it when he gets a chance. 👍

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` and new logo :)
Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by FluorescentHallucinogen** [comment]
@Urigo I like the new logo. ☺️
