### ISSUE TITLE
Command Injection vulnerability

### ISSUE THREAD

**Issue by ajmakhl** [Urigo/graphql-cli#454]
**Describe the bug**
When I install graphql-cli I get **found 4 vulnerabilities (3 moderate, 1 critical)**.
 

**To Reproduce**
1. ```mkdir example```
2. ```cd example/```
2. ```npm init -y```
3. ```npm install --save graphql-cli```

**Expected behavior**
I should see 0 vulnerabilities or at least no **critical** ones.

**Screenshots**
<img width="568" alt="Screen Shot 2019-03-30 at 7 29 22 AM" src="https://user-images.githubusercontent.com/17507288/55275547-1fa9db00-52be-11e9-9c24-dd20a0b82bf1.png">
 - OS: [`macOS Mojave`] 
 - `graphql-cli`: [`^3.0.11`]
**Additional context**
I just want to know if this is going to be a problem if I push my app to production.

**Comment by RemicsTech** [comment]
@ajmakhl I have the same problem too. Did you find anything?

**Comment by benoitDD** [comment]
For the critical vulnerability, the module `sync-exec` is [vulnerable](https://snyk.io/vuln/npm:sync-exec)
It is in 
```
-- graphql-cli@3.0.11
  -- npm-run@4.1.2
    -- sync-exec@0.6.2`
```

The version npm-run@5.0.1 correct this problem.

Can you upgrade npm-run to 5.0.1 ?

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0`.
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new new alpha version channel for GraphQL CLI - `4.0.0-alpha.XXX` !!

We've updated all the dependencies.

Checkout the [new instructions](https://github.com/urigo/graphql-cli#usage--initialization) and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) on the docs and let us know if you experience any more issues!
