### ISSUE TITLE
Is it possible to avoid printing the timestamp when running get-schema for example in ci?

### ISSUE THREAD

**Issue by dbertella** [Urigo/graphql-cli#458]
Is there a way to avoid printing the timestamp in the generated schema?
Happy to provide a pr if you think this it can be useful

**Comment by skywickenden** [comment]
Would also love this. Very annoying to have the schema file change with nothing new in it but the timestamp. Makes commits annoying and an easy source of conflict.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use GraphQL Code Generator plugin of GraphQL CLI with Codegen's `schema-ast` plugin. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
