### ISSUE TITLE
Unknown argument: boilerplate

### ISSUE THREAD

**Issue by ghiblin** [Urigo/graphql-cli#467]
**Describe the bug**
When adding boilerplate option flag to graphql create command it fails with "Unknown argument: boilerplate" error.

**To Reproduce**
npm install -g graphql-cli
graphql create myapp --boilerplate typescript-advanced

**Expected behavior**
To create a project with the selected template

**Versions (please complete the following information):**
 - OS: Windows 10
 - `graphql-cli`: 3.0.11

**Comment by beeman** [comment]
Fixed in #473

**Comment by ZiQiLN** [comment]
Same issue was posted at #471, Now you're supposed to use `graphql create <app>`.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use `init` command of GraphQL CLI with Graphback. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We have just released a new structure for GraphQL CLI in new alpha versions channel - `4.0.0-alpha.XXX`!

We suggest to use the `init` command of GraphQL CLI which was completely rewritten! 

Checkout the [new instructions](https://github.com/urigo/graphql-cli#usage--initialization) and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) on the docs and let us know your feedback during that alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by beeman** [comment]
Hey @Urigo, looks like the Discord invite link is expired:

![image](https://user-images.githubusercontent.com/36491/67798945-78a74080-fa52-11e9-96eb-03c361bd0c99.png)

**Comment by Urigo** [comment]
@beeman hmm that should expired....
I've opened a ticket to Discord.

In the meantime try: https://discord.gg/VZXRRmF

**Comment by Urigo** [comment]
Ohh wait, it's the wrong link!

This is the correct one: https://discord.gg/xud7bH9

**Comment by beeman** [comment]
> Ohh wait, it's the wrong link!
> 
> This is the correct one: https://discord.gg/xud7bH9

Thanks, that worked 👍🏼
