### ISSUE TITLE
The --boilerplate option has been removed without providing an alternative

### ISSUE THREAD

**Issue by beeman** [Urigo/graphql-cli#471]
**Describe the bug**

In [this commit](https://github.com/graphql-cli/graphql-cli/commit/39d5ba421b451cd76dfb0c81b630d1dadecb0cd3) the `--boilerplate` option has been removed without providing an alternative or a clear reason why.

This breaks various scripts and documentation on various sites and books (including the one I'm writing).

I would love to see the option back. 

**To Reproduce**
1. install `graphql-cli` globally
2. Run `graphql create my-app --boilerplate typescript-minimal`
3. An error occurs: `Unknown argument: boilerplate`

**Expected behavior**

The boilerplate should be selected based on the parameter.

**Screenshots**

**Versions (please complete the following information):**
 - OS: macOS Mojave 
 - `graphql-cli`: 3.0.11

**Additional context**
I will see if I can add a PR that makes it work again.

Somehow it also seems to [disable](https://github.com/graphql-cli/graphql-cli/commit/39d5ba421b451cd76dfb0c81b630d1dadecb0cd3#diff-f41e9d04a45c83f3b6f6e630f10117feR29) the `update-notifier`.

**Comment by janaka** [comment]
Workaround: run the command without the --boilerplate option which will present an interactive menu to chose a boilerplate. 

`graphql create my-app`

Helped me get post this roadblock. Still annoyed that the parameter being dropped caused me to waste time getting distracted from the main task at hand.

**Comment by ZiQiLN** [comment]
If you want to implement and sepcific boilerplate now, use a following scheme `graphql create react-fullstack-basic my-app`.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use `init` command of GraphQL CLI with Graphback. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We have just released a new structure for GraphQL CLI in new alpha versions channel - `4.0.0-alpha.XXX`!

We suggest to use the `init` command of GraphQL CLI which was completely rewritten! 

Checkout the [new instructions](https://github.com/urigo/graphql-cli#usage--initialization) and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) on the docs and let us know your feedback during that alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
