### ISSUE TITLE
Diff between schemaFile and endpoint can result in false negative

### ISSUE THREAD

**Issue by xzyfer** [Urigo/graphql-cli#475]
**Describe the bug**
Doing a diff between a `schemaPath` and an endpoint can result in a false negative if the schema doesn't reference all scalar types.

**To Reproduce**
1. Create a simple schema as `test.graphql`
```gql
schema {
  query: RootQuery
}

type RootQuery {
  foo: Foo
}

type Foo {
  id: String
}
```
2. Serve the schema locally
```
npx -p graphql -p @graphql-inspector/cli -c "graphql-inspector serve test.schema"
```
3. Create a `.graphqlconfig` for the schema
```js
{
  "projects": {
    "test": {
      "schemaPath": "test.graphql",
      "extensions": {
        "endpoints": {
          "local": "http://localhost:4000"
        }
      }
    },
  }
}
```
4. Run the `diff` command
```
npx graphql-cli diff --project test --endpoint local
```
5. See the report differences
```
--- local (http://localhost:4000)	removed
+++ a.graphql	added
@@ -1,8 +1,4 @@
-schema {
-  query: RootQuery
-}
-
 type Foo {
   id: String
 }


BREAKING CHANGES:
  ✖ Int was removed.
  ✖ Float was removed.
  ✖ ID was removed.
```

**Expected behavior**
No changes should be reported.

**Versions (please complete the following information):**
 - OS: macOS Mojave 
 - `graphql-cli`: 3.0.11

**Comment by xzyfer** [comment]
Any thoughts on this?

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use `diff` plugin of GraphQL CLI with GraphQL Inspector's diff commannd. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released new alpha versions channel for GraphQL CLI -  `4.0.0-alpha.XXX`!

We use [GraphQL Inspector](https://graphql-inspector.com) as the default package for the `diff` command to track changes between schemas.

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during that alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
