### ISSUE TITLE
Using `get-schema`, do `#` style comments get converted to `"""` style documentation?

### ISSUE THREAD

**Issue by jsonsivar** [Urigo/graphql-cli#505]
**Describe the bug**
More like a question than a bug, but when running `graphql get-schema` on a source file that has comments in the form `# comments meant to be hidden from gql clients`, they are converted to documentation comments like `""" this comment is visible in the playground documentation """`. Is this intentional and any reason for it? Or maybe something with my configuration.

**To Reproduce**
1. Create a schema file that has a # style comment and have that exposed on a service.
2. Then run `graphql get-schema` using a config file as below.
3. Look in the output file and see that the comments have been converted.

**Expected behavior**
Output schema should have the same style of comments as the input file.  Maybe there is a good reason for this or I am not configuring it properly so originally wanted it post this as a question instead of a bug.

**Screenshots**

**Versions (please complete the following information):**
 - Ubuntu 19.04
 - `"graphql-cli": "^3.0.11",`
 - `"apollo-link-http": "^1.5.5",`
 - `"apollo-server": "^2.1.0",`

**Additional context**

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use GraphQL Code Generator plugin of GraphQL CLI with Codegen's `schema-ast` plugin. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH
