### ISSUE TITLE
Create README.md for individual commands

### ISSUE THREAD

**Issue by wtrocki** [Urigo/graphql-cli#542]
## .Motivation

Commands are currently living as separate packages that are utilized by graphql-cli. 
Having some minimal readme for those will help people to know how to use them.

For example README.md can have information that this package is part of the cli and what it does in a couple sentences. I'm happy to contribute to that change

**Comment by Urigo** [comment]
that's a good idea and we would be very happy for the contribution!
I would also be cool because it can describe that higher reason for the command and then many different tools can implement each command and offer to serve it's purpose
