### ISSUE TITLE
Install  graphql-cli@next with npm failing

### ISSUE THREAD

**Issue by idkjs** [Urigo/graphql-cli#552]
**Describe the bug**

Running `[master*]npm i -g graphql-cli@next` fails:

**To Reproduce**
1. Open terminal
2. Run `npm i -g graphql-cli@next`
3. See error:
```
[master*]npm i -g graphql-cli@next
npm ERR! code ETARGET
npm ERR! notarget No matching version found for graphql-cli@next.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/prisc_000/.npm/_logs/2019-10-28T13_14_02_886Z-debug.log
```

**Expected behavior**
Installing with npm works.

**Versions (please complete the following information):**
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95
yarn version: 1.19.1
node version: v12.0.0

**Comment by idkjs** [comment]
Apparently it works with `npm i -g graphql-cli@4.0.0-alpha-3`. Installing with `yarn` will prompt you to select a version when using the `yarn add global graphql-cli@next` command suggested in Readme.md

**Comment by ardatan** [comment]
@idkjs Thank you for reporting this issue. We updated README file according to the latest changes. Now you can use `graphql-cli@4.0.0-alpha.15` instead.
