### ISSUE TITLE
Template / Plugins description system

### ISSUE THREAD

**Issue by peterdresslar** [Urigo/graphql-cli#568]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to request and display metadata along with each GraphQL CLI system. Items like name and description, as well as class, could be specified as required attributes in package.json, or similar. 

**Describe the solution you'd like**
Gatsby does this very well with Starters and with Plugins

**Additional context**
Implementing would likely affect the entire guild ecosystem, but also affect the inquiry system in the CLI script and the packaging of the Template projects

**Comment by wtrocki** [comment]
Really interesting. Any link to gatsby example?

**Comment by wtrocki** [comment]
I think we have improved commands by adding docs for publishing commands. We also moved to yargs. 
There is also a help system that brings commands to help. 
The commands currently coming from the entire guild ecosystem.

**Comment by wtrocki** [comment]
Feel free to reopen with more info
