### ISSUE TITLE
graphql command without parameters

### ISSUE THREAD

**Issue by wtrocki** [Urigo/graphql-cli#570]
graphql command without parameters should print list of commands with descriptions. Currently prints long stack trace.

**Comment by ardatan** [comment]
@wtrocki The problem is how to scan available npm packages that are also plugins. Do you have any idea to manage that?

**Comment by wtrocki** [comment]
@ardatan I think that Cli should have explicitly linked the core commands. Then features like command completion or help are easy. The previous version of cli was doing it:

https://github.com/Urigo/graphql-cli/tree/v3.0.13

**Comment by wtrocki** [comment]
Upon investigation - this will require rewrite of the plugin engine so it is not worth it. We can print custom help

**Comment by ardatan** [comment]
We are now printing commands right now.
