### ISSUE TITLE
[Disscussion] Template definitions inside repository 

### ISSUE THREAD

**Issue by wtrocki** [Urigo/graphql-cli#577]
Currently adding additional templates is limited as the standard templates offer configuration.
For future, it will be essential to have some template definition in the root repository so it will be possible to define it there rather than having it hard coded inside cli - as this requires releases.

https://github.com/Urigo/graphql-cli/blob/master/packages/commands/init/src/index.ts#L10-L50

**Comment by ardatan** [comment]
Right now, it downloads the template list from the repository;
https://github.com/Urigo/graphql-cli/blob/master/templates.json
