### ISSUE TITLE
Cannot install 4.x.x with @canary

### ISSUE THREAD

**Issue by digeomel** [Urigo/graphql-cli#655]
When I do `npm i -g graphql-cli@canary` as in the instructions to migrate from 3.x.x to 4.x.x, I get version `2.2.1-alpha-5cb7975.435`.
In fact, when I list the available channels and versions, I see this:
```
λ npm dist-tag ls graphql-cli
beta: 2.16.0-beta.7
canary: 2.2.1-alpha-5cb7975.435
latest: 3.0.14
```
I'm on Windows 10, npm version is 6.4.1 and node version is 10.13.0.
What am I missing?

**Comment by ardatan** [comment]
We have problems with version numbering in canary versions so that version you use is latest canary. :)

**Comment by digeomel** [comment]
@ardatan but I read in other comments that there are some 4.x.x versions that people can install. How do I install these? Do I even need to?

**Comment by ardatan** [comment]
No you don’t need to. The version you use is the latest. We are currently trying to fix this weird version numbers issue
