### ISSUE TITLE
Ideas for graphql-cli v3

### ISSUE THREAD

**Issue by kbrandwijk** [Urigo/graphql-cli#73]
### Background
As the `graphql-cli` ecosystem grows, and more commands are added, either to the core, or by plugins, use cases are emerging for a better way for different commands/plugins to interact with each other. This proposal addresses those use cases. It is heavily inspired by the `serverless` [plugin system](https://serverless.com/framework/docs/providers/aws/guide/plugins/).

### Command lifecycle events
Each command will define a number of lifecyle events. `graphql-cli` will create additional events for `before` and `after`, so for each defined lifecycle event a total of three events is generated. All of those events are executed sequentially. For example, let's take the `get-schema` command. This command downloads an introspection schema, and saves it to disk. It could define the following lifecycle event:
- `download`
For this lifecycle events, `graphql-cli` would generate the following events:
- `before:get-schema:download`
- `get-schema:download`
- `after:get-schema:download`

### Event hooks
To implement a command, you define the implementation for the lifecycle events by defining hooks. In our `get-schema` case, we want to implement the `get-schema:download` hook. 

### Additional events
In case of the `get-schema` example, there is a problem. Although `download` is the only lifecycle event that is triggered automatically when the command is executed, there is also functionality to update the schema when a new schema is downloaded. As this doesn't happen when the schema is unchanged, we don't want this event to be triggered automatically. But we want `graphql-cli` to expose events for this update step, so other plugins can hook into it. For this purpose, an 'internal' command can be defined, that can't be invoked by the user. For this, the context will expose a method: `context.run('get-schema.update')`. See the example below.

### Hooking into existing events
In the example above, we implemented our own `get-schema:download` hook. However, it is possible to define an implementation for any hook from any plugin. For example, there could be a backup plugin that implements the `before:get-schema:update:save` hook to create a backup copy of a schema file, before it is overwritten.

### Command is optional
In the current implementation, a plugin is a command. In the new system, a command is optional. This is because a plugin can hook into any event from any plugin, without defining any command of its own (like the backup example above). The plugin can also expose only internal commands, to provide hooks for other plugins.

### Execution order
When different plugins are going to hook into each others events, execution order becomes important. For this, the proposal includes explicitly defining the plugins you want to use in the `.graphqlconfig.yml` file, so they will execute in the order defined there.

### Example
Again, taking the `get-schema` command as example, this is what it would look like. The structure might change, because it might be possible to align it with the current `yargs` command structure.
```typescript
export const commands = {
  'get-schema': {
    description: 'Download schema from endpoint',
    lifecycle: [ 'download' ],
    options: {
      watch: {
        alias: 'w',
        boolean: true,
        description: 'watch server for schema changes and update local schema',
      },
      endpoint: {
        alias: 'e',
        describe: 'Endpoint name',
        type: 'string',
      },
    },
    commands: {
      update: {
        type: 'internal',
        lifecycle: [ 'save' ]
      }
    }
  }
}

export const hooks = {
  'get-schema:download': download,
  'get-schema:update:save': save
}

function download(context, args) {
  if (args.watch) {
    // While true call downloadSchema, then wait
  } else {
    // Call downloadSchema
  }
}

function downloadSchema(...) {
  // Download schema
  if (schemaHasChanged) {
    context.run('get-schema.update')
  }  
}

function save(context, args) {
  // Save schema to disk
}
```

### TODO
- [ ] Investigate yargs command file compatibility
- [ ] Define how context and args are passed in (serverless uses a class, instead of separate exports)
- [ ] ...?

**Comment by kbrandwijk** [comment]
## Passing context to commands
The current implementation using a custom handler wrapper to pass in context to the commands. This makes it harder to work with the standard `CommandObject` interface, and it also makes it harder to test individual commands in isolation.

Yargs offers a standard way of passing context to commands, using the `parse` function that I think should be used instead of the custom handler wrapper.

**Comment by kbrandwijk** [comment]
## Adding more commands to manage configuration
For example, commands to manage endpoints (from #9)
- `graphql endpoint add` (with the current `add-endpoint` as alias for backwards compatibility)
- `graphql endpoint set header`
- `graphql endpoint remove header`
- `graphql endpoint set url`

Also, add the option to ask for or specify headers on `add-endpoint`/`endpoint add`.

**Comment by iamclaytonray** [comment]
If we add a watch mode, I think it would be good to clear the console before downloading any changes

**Comment by wtrocki** [comment]
I see that some of the ideas might apply, however it will be better to have them logged as separate issues. Closing but feel free to reopen or create separate issue with idea that our team can implement
