### ISSUE TITLE
Empty generated.graphql after generation

### ISSUE THREAD

**Issue by jycouet** [Urigo/graphql-cli#776]
**Describe the bug**
The file `server\src\schema\generated.graphql` is empty after `yarn graphql generate --backend`

**To Reproduce**
1. run `yarn graphql generate --backend`
4. The file `server\src\schema\generated.graphql` is generated... but empty

**Expected behavior**
A file with the right content

**Versions (please complete the following information):**
 - OS: `Windows 10`
 - `graphql-cli`: [e.g. `4.0.1-beta.1`]

**Comment by wtrocki** [comment]
Looks like issue is related to Windows 10. I will need some time to get this chenged

**Comment by jycouet** [comment]
I would like to close this issue since I think also that it's related to the other one #777
