### ISSUE TITLE
relation "note" does not exist

### ISSUE THREAD

**Issue by jycouet** [Urigo/graphql-cli#777]
**Describe the bug**
The server returns errors without any modification of the default init cmd.

**To Reproduce**
1. run `yarn start:server`
2. server is running
3. Go to `http://localhost:4000/graphql`
4. Run the query 
```
{
  findAllNotes{
    title
  }
}
```
5. Error: 
```
"message": "select * from \"note\" - relation \"note\" does not exist",
```

**Expected behavior**
An empty array, without any error

**Versions (please complete the following information):**
 - OS: `Windows 10`
 - `graphql-cli`: [e.g. `4.0.1-beta.1`]

**Comment by craicoverflow** [comment]
Hi @jycouet;

It looks like your database has not been created. Did you run `yarn graphql generate` and include `Database Creation and Migration` in your selection choice?

**Comment by wtrocki** [comment]
I think it might be related to the old version of the init command. 
I did not manage to replicate that issue myself but it shows that there might be some dependency issues that we will need to track.

I could not replicate this issue but I think this could be related to the fact that Windows 10 is an Operatiing system. I will try to find Windows machine and try to replicate the issue:

Smilar issue happens here
https://github.com/Urigo/graphql-cli/issues/776

**Comment by jycouet** [comment]
Thx for your comments. 
With your hints, I looked a bit more into postgres & docker and it seems to be this the issue.

Here is the log after the first: `docker-compose up`:
```
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  |
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  |
postgres_1  | Data page checksums are disabled.
postgres_1  |
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting default timezone ... Etc/UTC
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
postgres_1  | performing post-bootstrap initialization ... ok
postgres_1  | syncing data to disk ... ok
postgres_1  |
postgres_1  | Success. You can now start the database server using:
postgres_1  |
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  |
postgres_1  |
postgres_1  | WARNING: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | waiting for server to start....LOG:  database system was shut down at 2020-01-09 20:43:03 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
postgres_1  |  done
postgres_1  | server started
postgres_1  | CREATE DATABASE
postgres_1  |
postgres_1  |
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  |
postgres_1  | waiting for server to shut down...LOG:  received fast shutdown request
postgres_1  | LOG:  aborting any active transactions
postgres_1  | LOG:  autovacuum launcher shutting down
postgres_1  | .LOG:  shutting down
postgres_1  | LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  |
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  |
postgres_1  | LOG:  database system was shut down at 2020-01-09 20:43:05 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
```

As you can see there is a `database system was shut down` in the middle of the process!
For sure it has nothing to do with **graphql-cli**.
I have no clue what could be wrong.

**Comment by wtrocki** [comment]
It appears to be problem with Windows 10.
https://stackoverflow.com/questions/37259584/postgres-shuts-down-immediately-when-started-with-docker-compose

We might check if we can swap postgres image that works on windows or investigate why this image fails to start.

**Comment by wtrocki** [comment]
@jycouet What form of CMD are you using on Windows? Do you have more information on what error happens. I cannot replicate it on bash and cannot even get any command working on powershell :D

**Comment by jycouet** [comment]
The error I posted here was with `git bash`.
The first challenge is to have docker working... :s

**Comment by wtrocki** [comment]
@jycouet GraphQL Init supports SQLLite out of the box. Generally windows platform is quite bad in pure form, but once you get ubuntu bash shell things work quite nicely. 
https://tutorials.ubuntu.com/tutorial/tutorial-ubuntu-on-windows#0

**Comment by jycouet** [comment]
I did what you suggested (ubuntu-on-windows) and I get the cmd to work.
But, docker daemon is not supported there. So I need to run the daemon on my windows... And like this I get the exact same error as before. Strange that you managed to make it worked.

How can I try with SQLLite? :)

**Comment by wtrocki** [comment]
Simply replace your configuration from pg to SQL Lite. 
Example: https://github.com/aerogear/graphback/blob/master/examples/generator-fullstack/graphback-sqllite.json#L2-L7

**Comment by jycouet** [comment]
I confirm that on linux it's working just great!
![image](https://user-images.githubusercontent.com/5312607/72378475-c4908a00-3711-11ea-92f7-732bc14577bf.png)

I suggest to close the issue, I'll look later for windows.
@wtrocki I let you do it?

**Comment by wtrocki** [comment]
We are in the process of doing basic automation to verify some commands. We going to do it for windows as well. This will make sure that our stuff works without  installing windows vms
