### ISSUE TITLE
Running simple queries with v4

### ISSUE THREAD

**Issue by szepeviktor** [Urigo/graphql-cli#831]
After reading that `graphql query` is gone, please advise how to run queries from the command line?

```graphql
query Admins {
  users(where: { role: ADMIN }) {
    email
  }
}
```

Thank you.

**Comment by wtrocki** [comment]
From my point of view, this looks like a really nice idea for community plugin. w
Keep in mind that there is vscode extension that works with graphql-config so queries can be made in vscode :D

**Comment by szepeviktor** [comment]
> From my point of view, this looks like a really nice idea for community plugin.

Thank you.

> Keep in mind that there is vscode extension that works with graphql-config so queries can be made in vscode :D

I work on remote terminals only, and developing solutions for CI, so I do not use an IDE.

**Comment by szepeviktor** [comment]
Do I understand correctly that running a query is simply missing from v4?

**Comment by wtrocki** [comment]
This project might be interesting:
https://github.com/hasura/graphqurl

We might consider creating community plugin that base on this

**Comment by wtrocki** [comment]
Alternative was found. Closing
