### ISSUE TITLE
No possibility to extend init method for your own template

### ISSUE THREAD

**Issue by wtrocki** [Urigo/graphql-cli#903]
GraphQL init contains set of really useful commands but they cannot be used beyond 2 core templates.

https://github.com/Urigo/graphql-cli/blob/master/packages/commands/init/src/index.ts#L401

**Comment by ardatan** [comment]
There is an option called `Other Template`;
https://github.com/Urigo/graphql-cli/blob/b902782f40c68223302d40ed5e6abf0c0cf6b0cb/packages/commands/init/src/index.ts#L181
Isn't that what you ask? People can enter their own repository using this option.

**Comment by wtrocki** [comment]
I'm currently working on improving init and generate and assigned that to myself after recieving feedback that is hard to add things to the existing project. This option doesn't help much as it will not setup project template: https://github.com/Urigo/graphql-cli/blob/b902782f40c68223302d40ed5e6abf0c0cf6b0cb/packages/commands/init/src/index.ts#L198

And thus this is reducing a number of benefits from init. I'm looking for the equivalent of `graphback config` cmd etc. that is much more generic. 
https://graphback.dev/docs/gettingstarted#adding-graphback-to-existing-project-using-graphback-cli

**Comment by ardatan** [comment]
@wtrocki we can seperate init command into two different ones. First one would create a project from scratch using Graphback and the other one would create only config file for an existing project. What do you think?

**Comment by wtrocki** [comment]
Great idea. What I'm doing now is porting graphback to use graphql-config. Once that is done we can practically do 2 commands - config and init all driven by adding some graphql-codegen-plugins and graphback plugins (we can ask couple questions here)

**Comment by wtrocki** [comment]
Going to work on some raw idea and create PR soon

**Comment by wtrocki** [comment]
Update. Init method can use now graphback config to initialize configuration and then later extend it by codegen etc. Creating PR
