### ISSUE TITLE
Unable to generate resolvers with Backend template.

### ISSUE THREAD

**Issue by cecobask** [Urigo/graphql-cli#906]
I generated a project with `graphql init` and chose Backend option. Afterwards, I was unable to generate resolvers.

1. `graphql init`
2. Pick Backend option.
3. I want to create a new project from a GraphQL CLI Project Template.
4. `graphql generate --db`
5. `graphql generate --backend`
6. Errors:
![image](https://user-images.githubusercontent.com/32335835/73883317-a1ae4d00-485b-11ea-9c0a-3c007ba62144.png)

**Expected behavior**
Expected to see resolvers generated for the project.

**Versions (please complete the following information):**
 - OS: [`Ubuntu 18.04`] 
 - `graphql-cli`: [e.g. `4.0.1-alpha-40077ee.127`]

**Comment by AlexQuidditch** [comment]
same problem

**Comment by wtrocki** [comment]
Sorry for long lack of updates. We are about to release new version.

**Comment by wtrocki** [comment]
We have fixed fullstack template and working on disabling badkend. 
Backend has the same codebase as fullstack, while is missing example application that can be useful to explore graphql API etc.
