### ISSUE TITLE
The full stack template gives an error in server

### ISSUE THREAD

**Issue by udith-shalinda** [Urigo/graphql-cli#912]
The issue is with the typeDefs and resolvers in apolloServer.

```
const apolloServer = new ApolloServer({
    typeDefs: loadSchemaFiles(join(__dirname, '/schema/')),
    resolvers: loadResolversFiles(join(__dirname, '/resolvers/')),
    context: createKnexRuntimeContext(db as any, pubSub),
    playground: true,
  })
```

**Comment by wtrocki** [comment]
Apollo broke compatibility on their types. 
I'm currently refactoring this so going to assign it to myself. 
As a quick workaround, we can do `as any` or use `makeExecutableSchema` from graphql-toolkit

**Comment by wtrocki** [comment]
That is currently fixed. Updating to latest Graphback
